version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22  # Use a stable LTS version like 22
    commands:
      - echo "Node Version: $(node -v)"
      - echo "npm Version: $(npm -v)"
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the React app...
      - npm run build

  post_build:
    commands:
      - echo Build completed successfully!

artifacts:
  files:
    - '**/*'
  base-directory: build  # Adjust this if your build directory differs
  discard-paths: yes

cache:
  paths:
    - '/root/.npm/**/*'  # Cache npm dependencies for faster builds
